

USE DEVDOJO
GO


DROP TABLE IF EXISTS TBL_PESSOA
DROP TABLE IF EXISTS TBL_ENDERECO
DROP TABLE IF EXISTS TBL_TIPO_LOGRADOURO
DROP TABLE IF EXISTS TBL_TIPO_TELEFONE
DROP TABLE IF EXISTS TBL_TELEFONE
DROP TABLE IF EXISTS TBL_FUNCIONARIO
DROP TABLE IF EXISTS TBL_DIRETORIA
DROP TABLE IF EXISTS TBL_DEPARTAMENTO
GO


CREATE TABLE TBL_PESSOA(

    ID_PESSOA INT PRIMARY KEY IDENTITY(1, 1),
    
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO CHAR(1) NOT NULL


    CONSTRAINT ChecaTamanhoCPF CHECK(LEN(CPF) = 11),
    CONSTRAINT ChecaSexo CHECK (UPPER(SEXO) = 'M' OR UPPER(SEXO) = 'F')


)
GO

CREATE TABLE TBL_TIPO_LOGRADOURO(

    ID_TP_LOGRADOURO TINYINT PRIMARY KEY IDENTITY(1, 1),
    DESC_LOGRADOURO VARCHAR(40) NOT NULL UNIQUE CHECK (DESC_LOGRADOURO <> '')

)
GO

CREATE TABLE ENDERECO(

    ID_ENDERECO INT PRIMARY KEY IDENTITY(1, 1),
    ID_PESSOA INT NOT NULL,
    ID_TP_LOGRADOURO TINYINT NOT NULL,

    ENDERECO VARCHAR(80) NOT NULL CHECK(ENDERECO <> ''),
    NUMERO INT NOT NULL,
    COMPLEMENTO VARCHAR(40),
    CEP VARCHAR(8) NOT NULL,



    CONSTRAINT FK_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TBL_PESSOA (ID_PESSOA),
    CONSTRAINT FK_ID_LOGRADOURO FOREIGN KEY (ID_TP_LOGRADOURO) REFERENCES TBL_TIPO_LOGRADOURO (ID_TP_LOGRADOURO)


)
GO

CREATE TABLE TBL_TIPO_TELEFONE(

    ID_TP_TELEFONE TINYINT PRIMARY KEY IDENTITY(1, 1),
    TIPO_TELEFONE VARCHAR(15) NOT NULL UNIQUE CHECK (TIPO_TELEFONE <> '')

)
GO

CREATE TABLE TBL_TELEFONE(

    ID_TELEFONE INT PRIMARY KEY IDENTITY(1, 1),
    ID_PESSOA INT NOT NULL,
    ID_TP_TELEFONE TINYINT NOT NULL,
    DDD VARCHAR(2) NOT NULL,
    NUMERO VARCHAR(9) NOT NULL

    CONSTRAINT CHECA_ID_PESSOA_TELEFONE CHECK (ID_PESSOA <> ''),
    CONSTRAINT CHECA_DDD CHECK (DDD <> ''),
    CONSTRAINT CHECA_NUMERO CHECK (NUMERO <> ''),
    CONSTRAINT FK_ID_PESSOA_TELEFONE FOREIGN KEY (ID_PESSOA) REFERENCES TBL_PESSOA (ID_PESSOA),
    CONSTRAINT FK_ID_TP_TELEFONE FOREIGN KEY (ID_TP_TELEFONE) REFERENCES TBL_TIPO_TELEFONE (ID_TP_TELEFONE)


)
GO

CREATE TABLE TBL_DIRETORIA(
    ID_DIRETORIA TINYINT PRIMARY KEY IDENTITY(1, 1),
    COD_DIR VARCHAR(5) NOT NULL UNIQUE CHECK (COD_DIR <> ''),
    DIRETORIA VARCHAR(30) NOT NULL UNIQUE CHECK (DIRETORIA <> '')
)
GO

CREATE TABLE TBL_DEPARTAMENTO(
    ID_DEPARTAMENTO TINYINT PRIMARY KEY IDENTITY(1, 1),
    COD_DEPARTAMENTO VARCHAR(5) NOT NULL,
    DEPARTAMENTO VARCHAR(30) NOT NULL UNIQUE CHECK(DEPARTAMENTO <> ''),

    CONSTRAINT UqCodDepartamento UNIQUE (COD_DEPARTAMENTO),
    CONSTRAINT ChCodDep CHECK (COD_DEPARTAMENTO <> '')
)



CREATE TABLE TBL_FUNCIONARIO(

    MATRICULA INT PRIMARY KEY IDENTITY(1000, 1),
    ID_PESSOA INT NOT NULL,
    DT_ADMISSAO DATE NOT NULL,
    DT_DEMISSAO DATE,
    SALARIO FLOAT NOT NULL CHECK (SALARIO > 1200),


    ID_CARGO SMALLINT NOT NULL,
    ID_DEPARTAMENTO TINYINT NOT NULL,
    ID_NIVEL_FUNCIONARIO TINYINT NOT NULL,

    CONSTRAINT ID_PESSOA_FUNCIONARIO FOREIGN KEY (ID_PESSOA) REFERENCES TBL_PESSOA (ID_PESSOA),

   
)
GO



