

SELECT GETDATE() AS [GETDATE()],
       CURRENT_TIMESTAMP AS [CURRENT_TIMESTAMP],
       SYSDATETIME() AS [SYSDATETIME()],
       GETUTCDATE() AS [GETUTCDATE()],
       SYSUTCDATETIME() AS [SYSUTCDATETIME],
       SYSDATETIMEOFFSET() AS [SYSDATETIMEOFFSET]

